name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 4: Build with Maven
    - name: Build with Maven
      run: mvn clean package

       # Step 6: Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/maven-app:latest .

    # Step 7: Push Docker Image to Docker Hub
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/maven-app:latest

    # Step 8: Run Docker Container (Testing)
    - name: Run Docker Container
      run: |
        docker run --name maven-app-test -d -p 8088:8080 ${{ secrets.DOCKER_USERNAME }}/maven-app:latest
        sleep 10
        docker ps
        docker logs maven-app-test
        docker stop maven-app-test
        docker rm maven-app-test
